### ISSUE TITLE
[1.9] Entity vanish when loading a saved game

### ISSUE THREAD

**Issue by tomevoll** [MinecraftForge/MinecraftForge#2623]
Spawning a Entity seems to work ok until you save the game then load it again, they show up then vanish after 5 sec, hitting it causing damage by using a ender pearl to tp threw the entity will make it visible again.

Example here [https://www.youtube.com/watch?v=azjDDvU-Z-A&feature=youtu.be](url)

**Comment by LexManos** [comment]
Update Forge and post logs. This looks like the position issue that was fixed a while ago.
Closing until you verify it's a real issue on Forge's end.

**Comment by tomevoll** [comment]
Its still a issue in 16.0.1797
Not sure what logs to show you, there is no errors, 

To duplicate create a EntityCreature register it using EntityRegistry.registerModEntity(entityClass, Id, 0, this, 64, 1, true);

Spawn in the entity using world.spawnEntityInWorld

Entity stays visible until you save the game as i show in that video.

**Comment by williewillus** [comment]
Anyhow, this is a duplicate of #2567

**Comment by tomevoll** [comment]
by checking the entity both server and client side, the position is matching, seems to be something else going on. server position stays 0 on server side pos is correct, client side serverpos is in the thousands, while posX-Z match posX-Z on server, trying to set the position manually on client still dont show the entity, i might be testing this the wrong way
